const polyglot = new Polyglot();

const translations = {
    en: {
        "header.name": "Vladislav Buyanov",
        "header.profession": "Python Developer",
        "resume.download": "Download Resume",
        "about_me.title": "About me",
        "about_me.p1": "My name is Vladislav. I am a QA automation engineer. My goal is to continuously improve myself and become a backend developer.",
        "about_me.p2": "In the world of development, I find inspiration in creating complex logical structures and working with databases. My passion is to build technological solutions that make the world more efficient and convenient.",
        "about_me.p3": "In my free time, I do sports, read, and watch TV shows. I believe that regular breaks and variety in life not only help to maintain balance but also make me more productive at work.",
        "about_me.p4": "I am always open to new connections and happy to discuss opportunities for collaboration in backend development or programming in general.",
        "about_me.p5": "Please feel free to get in touch!",
        "work_experience.title": "Work experience",
        "work_experience.period": "01.04.2023 - Now",
        "work_experience.job_title_label": "Job Title:",
        "work_experience.job_title": "QA automation.",
        "work_experience.responsibilities_label": "Responsibilities:",
        "work_experience.responsibilities": "Conducting manual testing and developing automated tests for our team's applications. I actively engage in load testing and have experience in developing my own tool for conducting load testing.",
        "work_experience.technologies_label": "Technologies Used:",
        "work_experience.technologies": "Python, Selenium, Locust, Docker, Databases, Command Line, Git, TestRail.",
        "skills.title": "My skills",
        "skills.technical": "Technical skills",
        "skills.web": "Web-Development:",
        "skills.frontend": "Frontend:",
        "skills.data": "Data:",
        "skills.qa": "QA:",
        "skills.infrastructure": "Infrastructure:",
        "skills.processes": "Processes:",
        "skills.soft": "Soft-Skills",
        "skills.soft.learning": "Like to learn new things",
        "skills.soft.teamwork": "Team player",
        "skills.soft.flexible": "Flexible",
        "skills.languages": "Languages",
        "skills.lang.english": "English language - B2",
        "skills.lang.slovak": "Slovak language - B2",
        "skills.lang.russian": "Russian language - Native",
        "projects.title": "Pet Projects",
        "projects.haja.title": "Haja S.R.O. webpage",
        "projects.haja.desc": "Web-page for 'Haja S.R.O.'",
        "projects.museum.title": "Brhlovce Municipal Museum",
        "projects.museum.desc": "Local museum website",
        "projects.lib.title": "Small Lib",
        "projects.lib.desc": "Web service for exchanging books",
        "projects.agri.title": "AGRI bot",
        "projects.agri.desc": "Telegram bot providing data on prices for wheat, corn and rapeseed from Central European Commission.",
        "projects.tech": "Tech:"
    },
    ru: {
        "header.name": "Владислав Буянов",
        "header.profession": "Разработчик Python",
        "resume.download": "Скачать резюме",
        "about_me.title": "Обо мне",
        "about_me.p1": "Меня зовут Владислав. Я инженер по автоматизации тестирования. Моя цель — постоянно развиваться и стать бэкенд-разработчиком.",
        "about_me.p2": "В мире разработки я черпаю вдохновение от создания сложных логических структур и работы с базами данных. Моя страсть — создание технологических решений, делающих мир эффективнее и удобнее.",
        "about_me.p3": "В свободное время я занимаюсь спортом, читаю книги и смотрю сериалы. Я верю, что регулярные перерывы и разнообразие в жизни не только помогают поддерживать баланс, но и делают меня более продуктивным на работе.",
        "about_me.p4": "Я всегда открыт новым связям и рад обсудить возможности сотрудничества в области бэкенд-разработки или программирования в целом.",
        "about_me.p5": "Пожалуйста, не стесняйтесь со мной связаться!",
        "work_experience.title": "Опыт работы",
        "work_experience.period": "01.04.2023 — Настоящее время",
        "work_experience.job_title_label": "Должность:",
        "work_experience.job_title": "Автоматизация тестирования.",
        "work_experience.responsibilities_label": "Обязанности:",
        "work_experience.responsibilities": "Проведение ручного тестирования и разработка автоматизированных тестов для приложений нашей команды. Я активно участвую в нагрузочном тестировании и имею опыт разработки собственного инструмента для его проведения.",
        "work_experience.technologies_label": "Используемые технологии:",
        "work_experience.technologies": "Python, Selenium, Locust, Docker, Базы данных, Командная строка, Git, TestRail.",
        "skills.title": "Мои навыки",
        "skills.technical": "Технические навыки",
        "skills.web": "Веб-разработка:",
        "skills.frontend": "Фронтенд:",
        "skills.data": "Данные:",
        "skills.qa": "Тестирование:",
        "skills.infrastructure": "Инфраструктура:",
        "skills.processes": "Процессы:",
        "skills.soft": "Soft-skills",
        "skills.soft.learning": "Люблю учиться новому",
        "skills.soft.teamwork": "Командный игрок",
        "skills.soft.flexible": "Гибкость",
        "skills.languages": "Языки",
        "skills.lang.english": "Английский язык — B2",
        "skills.lang.slovak": "Словацкий язык — B2",
        "skills.lang.russian": "Русский язык — Родной",
        "projects.title": "Персональные проекты",
        "projects.haja.title": "Веб-сайт компании Haja S.R.O.",
        "projects.haja.desc": "Веб-сайт для 'Haja S.R.O.'",
        "projects.museum.title": "Муниципальный музей Брхловце",
        "projects.museum.desc": "Веб-сайт местного музея",
        "projects.lib.title": "Small Lib",
        "projects.lib.desc": "Веб-сервис для обмена книгами",
        "projects.agri.title": "Бот AGRI",
        "projects.agri.desc": "Телеграм-бот, предоставляющий данные о ценах на пшеницу, кукурузу и рапс из Центральной Европейской комиссии.",
        "projects.tech": "Технологии:"
    },
    sk: {
        "header.name": "Vladislav Buyanov",
        "header.profession": "Vývojár Python",
        "resume.download": "Stiahnuť životopis",
        "about_me.title": "O mne",
        "about_me.p1": "Volám sa Vladislav. Som inžinier automatizácie testovania. Mojím cieľom je neustále sa rozvíjať a stať sa backend vývojárom.",
        "about_me.p2": "V svete vývoja nájdem inspiráciu v tvorbe komplexných logických štruktúr a práci s databázami. Moja vášeň je staviať technologické riešenia, ktoré robia svet účinnejším a pohodlnejším.",
        "about_me.p3": "Vo voľnom čase robím šport, čítam knihy a sledujem televízne seriály. Verím, že pravidelné prechody a variabilita v živote pomáhajú udržiavať rovnováhu a tiež ma robia produktívnejším pri práci.",
        "about_me.p4": "Vždy som otvorený novým kontaktom a rád diskutujem o možnostiach spolupráce v oblasti backend vývoja alebo programovania všeobecne.",
        "about_me.p5": "Neváhejte ma kontaktovať!",
        "work_experience.title": "Pracovné skúsenosti",
        "work_experience.period": "01.04.2023 – Teraz",
        "work_experience.job_title_label": "Pozícia:",
        "work_experience.job_title": "Automatizácia testovania.",
        "work_experience.responsibilities_label": "Odpovednosti:",
        "work_experience.responsibilities": "Provádzanie manuálneho testovania a vyvíjanie automatizovaných testov pre aplikácie našej tímu. Aktívne sa zaoberám testovaním záťaže a mám skúsenosti so vývojom vlastného nástroja pre jeho provádzanie.",
        "work_experience.technologies_label": "Použité technológie:",
        "work_experience.technologies": "Python, Selenium, Locust, Docker, Databázy, Príkazový riadok, Git, TestRail.",
        "skills.title": "Moje schopnosti",
        "skills.technical": "Technické schopnosti",
        "skills.web": "Webový vývoj:",
        "skills.frontend": "Frontend:",
        "skills.data": "Dáta:",
        "skills.qa": "Testovanie:",
        "skills.infrastructure": "Infraštruktúra:",
        "skills.processes": "Procesy:",
        "skills.soft": "Mäkké schopnosti",
        "skills.soft.learning": "Rád sa učím nové veci",
        "skills.soft.teamwork": "Tímový hráč",
        "skills.soft.flexible": "Prispôsobivý",
        "skills.languages": "Jazyky",
        "skills.lang.english": "Angličtina – B2",
        "skills.lang.slovak": "Slovenčina – Rodný",
        "skills.lang.russian": "Ruština – B2",
        "projects.title": "Osobné projekty",
        "projects.haja.title": "Webová stránka firmy Haja S.R.O.",
        "projects.haja.desc": "Webová stránka pre 'Haja S.R.O.'",
        "projects.museum.title": "Obecné múzeum Brhlovce",
        "projects.museum.desc": "Webová stránka miestneho múzea",
        "projects.lib.title": "Small Lib",
        "projects.lib.desc": "Webová služba na výmenu kníh",
        "projects.agri.title": "Bot AGRI",
        "projects.agri.desc": "Telegram bot poskytujúci informácie o cenách pšenice, kukurice a répa z Centrálnej európskej komisie.",
        "projects.tech": "Technológie:"
    },
};

function updateTexts() {
    document.querySelectorAll("[data-i18n]").forEach(el => {
        const key = el.getAttribute("data-i18n");
        el.textContent = polyglot.t(key);
    });
}

document.querySelectorAll(".lang-button").forEach(button => {
    button.addEventListener("click", () => {
        const newLang = button.dataset.lang;
        localStorage.setItem("lang", newLang);
        polyglot.replace(translations[newLang]);
        updateTexts();
    });
});
